apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sd831vika-java-springboot 
  janus-idp.io/tekton: sd831vika-java-springboot
  backstage.io/kubernetes-id: sd831vika-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sd831vika-java-springboot
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml